# Generated by Django 4.2.1 on 2023-05-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_alter_registro_bache'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='Desechos_Mora',
            new_name='Azucar',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='Paquete_250_gr',
            new_name='Bolsa_Cinco_kg',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='Bache',
            new_name='Canasta',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='Gramos_de_Azucar',
            new_name='Contenido_Total',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='Hora_Inicio',
            new_name='Empaque',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='Pausa_de_enfriado',
            new_name='Enfriamiento',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='Gramos_de_Mora',
            new_name='Fruta_Seleccionada',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='Primer_Hervor',
            new_name='Inicio',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='Paquete_5000_gr',
            new_name='Libra',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='Paquete_500_gr',
            new_name='Media_Libra',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='Ultima_Coccion',
            new_name='Primera_Coccion',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='Gramos_de_Sorbato',
            new_name='Producto_no_Conforme',
        ),
        migrations.AddField(
            model_name='registro',
            name='Otro',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='Producto_Terminado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registro',
            name='Segunda_Coccion',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='registro',
            name='Sorbato',
            field=models.FloatField(default=0.0),
        ),
    ]
